name: CI

on:
  push:
    branches: 
      - feature-*

jobs:
  execute_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Verify style with flake
        run: flake8 tests/ calculs/

      - name: Verify type with mypy
        run: mypy .

      - name: Launching tests
        run: |
          pytest --cov=calculs --cov-report=term-missing --cov-fail-under=90

      - name: Create exec (build)
        run: pyinstaller --onefile --name calculs main.py

      - name: Run python script
        run: python main.py
